# Generated by Django 4.1.7 on 2023-03-21 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsdetail',
            name='doctor_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dealsdetail',
            name='employee',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dealsdetail',
            name='product_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='employee',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='employee',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='employee',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_joining', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
