# Generated by Django 4.1.7 on 2023-03-21 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_dealsdetail_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 12, 11, 13, 194237, tzinfo=datetime.timezone.utc)),
        ),
    ]
