# Generated by Django 4.1.7 on 2023-03-21 12:11

import datetime
from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsdetail',
            name='employee',
            field=models.CharField(default=employee.models.Employee, max_length=256),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 12, 11, 57, 18931, tzinfo=datetime.timezone.utc)),
        ),
    ]
