# Generated by Django 4.1.7 on 2023-03-21 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_dealsdetail_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsdetail',
            name='employee',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 12, 12, 14, 811955, tzinfo=datetime.timezone.utc)),
        ),
    ]
